### ISSUE TITLE
Competitive programming

### ISSUE THREAD

**Issue by parthyadav3105** [turington/talks#2]
Ekam is going to be first talk of the new session, so we should have some elementary topics for freshers. Competitive programming can be one such topic. 

Is anyone interested in talking on this topic?

Topic: Getting Started with Competitive programming
Speaker:______
duration: 20 mins (max)
description: Introduction to standard input/output and solving 2 competitive problems. 
Useful links: [google io tutorial](https://code.google.com/codejam/resources/quickstart-guide#io-tutorial)

**Comment by Shubham8287** [comment]
i can ,but can we increase duration time approx (40-60) min?

**Comment by parthyadav3105** [comment]
Try to finish in 30 mins. Although if something goes wrong 40 mins will be feasible because it will he Saturday/Sunday.

**Comment by Shubham8287** [comment]
ok! assign me a date.

**Comment by parthyadav3105** [comment]
resolved: #2
