### ISSUE TITLE
Proposed Topic : Intro to App Development and Firebase

### ISSUE THREAD

**Issue by toseefkhan403** [turington/talks#5]
Topic: Intro to App Development and Firebase
Speaker: Toseef Ali Khan 
Duration: 30 mins
Description: Introduction, Android Apps: Basic to Advanced, Detailed intro to firebase(authentication, real-time database, storage, cloud functions etc), 
Intro to Cross-platform tool : flutter, using firebase with flutter.

**Comment by aarush-ittan** [comment]
congratulations @toseefkhan403 your talk has been selected for turing talks 2 . The talk is scheduled for 23 october . For more details pleases visit : For more details please visit : [readme.md](https://github.com/turington/talks/blob/master/README.md) on turing/talks page.
