### ISSUE TITLE
Intro to Open Source using GitHub.

### ISSUE THREAD

**Issue by iampavangandhi** [turington/talks#6]
Topic: Intro to Open Source using GitHub.
Speaker: Pavan Gandhi
Duration: 30 mins
Description: Why contribute to Open Source, How to contribute to Open Source, Some useful resources to learn.
Open Source Programs and Organisations: GSOC, RGSOC, FOSS, Mozila Winter of Security.

**Comment by sh4d0w-nixx** [comment]
congratulations @iampavangandhi  your talk has been selected for turing talks 2 . The talk is scheduled for 23 october . For more details pleases visit : For more details please visit : readme.md on turing/talks page.

**Comment by aarush-ittan** [comment]
congratulations @iampavangandhi your talk has been selected for turing talks 2 . The talk is scheduled for 23 october . For more details pleases visit :For more details please visit [readme.md](https://github.com/turington/talks/blob/master/README.md) on turing/talks page.
