### ISSUE TITLE
BLOCKCHAIN

### ISSUE THREAD

**Issue by vishnu82** [turington/talks#7]
Topic: blockchain
 Speaker: Vishnu singh
DURATION: 35 MINUTES
DESCRIPTION: INTRODUCTION , FEATURES , ADVANTAGES & IMPLMENTATION..

**Comment by sh4d0w-nixx** [comment]
congratulations @vishnu82  your talk has been selected for turing talks 2 . The talk is scheduled for 23 october . For more details pleases visit : For more details please visit : readme.md on turing/talks page.

**Comment by sh4d0w-nixx** [comment]
congratulations @toseefkhan403 your talk has been selected for turing talks 2 . The talk is scheduled for 23 october . For more details please visit [readme.md](https://github.com/turington/talks/blob/master/README.md) on turing/talks page.

**Comment by aarush-ittan** [comment]
congratulations @vishnu82  your talk has been selected for turing talks 2 . The talk is scheduled for 23 october . For more details pleases visit : For more details please visit [readme.md](https://github.com/turington/talks/blob/master/README.md) on turing/talks page.
